# Travis CI configuration file for running tests
language: python

python:
  - "2.7"
<<<<<<< HEAD
=======

services:
  - docker
  
>>>>>>> 743be6159a50602633a7673bdece7a259f60be26
addons:
  apt:
    packages:
      - nodejs
      - python-demjson
<<<<<<< HEAD
before_install:
  - sudo apt-get update
=======

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install -o Dpkg::Options::="--force-confold" docker-engine

>>>>>>> 743be6159a50602633a7673bdece7a259f60be26
install:
  - "pip install --allow-all-external -r requirements.txt"
  - "pip install --allow-all-external demjson"

env:
  - MAKE_TARGET=test.syntax
  - MAKE_TARGET=test.edx_east_roles
  - MAKE_TARGET=docker.test.shard SHARD=0 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=1 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=2 SHARDS=3

script:
  - docker --version
  - make --version
  - travis_wait 50 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS
