#!/usr/bin/env ansible-playbook
---
#
# When running this playbook you must use '--skip-tags="jenkins-seed-job"'
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: scheduler
  when: redeploy | default(False) | bool

- name: Deploy scheduler service
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: True
  vars:
    CLUSTER_NAME: scheduler
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
  roles:
    - role: jenkins_analytics
      tags: jenkins_analytics
