#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: xqueue
  when: redeploy | default(False) | bool
- name: "Setup {{ COMMON_HOSTNAME }}"
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: xqueue
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp-common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
  roles:
    - role: nginx
      tags: nginx
      nginx_sites:
        - xqueue
    - role: xqueue
      tags: xqueue
