- name: Start instance
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  vars:
    secure_dir: '../../../edx-secret/ansible'
    local_dir:  '../../../edx-secret/ansible/local'
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/{{ env }}/vars.yml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/shib_lagunita_vars.yml"
  tasks:
    - action: ec2_facts
    - name: Start instance
      local_action:
        module: ec2
        state: running
        region: us-west-1
        instance_ids: "{{ ansible_ec2_instance_id }}"
        wait: True
