- hosts: ~tag_Name_{{ machine }}_{{ env }}
  pre_tasks:
  - fail: msg="This playbook only runnable on 'app' machines"
    when: "'app' not in machine"
  sudo: True
  vars:
    secure_dir: '../../../edx-secret/ansible'
    local_dir:  '{{ secure_dir }}/local'
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/edxapp_{{ env }}_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
  roles:
    - common
    - role: user
      tags: users
    - supervisor
    - role: nginx
      nginx_sites:
        - lms
        - cms
      nginx_template_directory: "{{local_dir}}/nginx/templates/cme/"
      nginx_default_sites:
        - lms
    - {'role': 'edxapp', 'openid_workaround': true, 'template_subdir': 'cme'}
