- name: Basic util setup on all hosts
  # This uses variable expansion so you can select machine(s) from the command line
  # using the -e flag.  See README for instructions on how to use.
  hosts: ~tag_Name_{{machine}}_prod
  pre_tasks:
  - fail: msg="This playbook only runnable on 'util' machines"
    when: "'util' not in machine"
  sudo: True
  gather_facts: True
  vars:
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    secure_dir: '../../../configuration-secure/ansible'
    local_dir:  '{{secure_dir}}/local'
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/xqueue_prod_vars.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
  roles:
    - common
    - supervisor
    - role: user
      tags: users
    - role: nginx
      nginx_sites:
      - xqueue
      tags:
      - nginx
    - role: xqueue
      xqueue_create_db: "no"
      xqueue_create_users: false
      tags:
      - xqueue
