- hosts: tag_Name_jumpbox_prod
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/users_jumpbox.yml"
    - "{{ secure_dir }}/vars/datadog_prod.yml"
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir:  '../../../configuration-secure/ansible/local'
  roles:
    - common
    - supervisor
    - role: user
      tags: users
