# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{machine}}_prod
  pre_tasks:
  - fail: msg="This playbook only runnable on 'app' machines"
    when: "'app' not in machine"
  sudo: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../configuration-secure/ansible/local'
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/lagunita/users.yml"
    - "{{ secure_dir }}/vars/lagunita/shib.yml"
  roles:
    - common
    - edxapp
    - role: apache
      tags: apache
    - role: shibboleth
      tags: shibboleth
