---
- hosts: ~tag_Name_forum(1|2)_prod
  sudo: yes
  vars:
    secure_dir: ../../../configuration-secure/ansible
    local_dir: ../../../configuration-secure/ansible/local
  vars_files:
    - "{{secure_dir}}/vars/lagunita/forum.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
        - forum
    - forum
