---
- name: Common configuration for all staging hosts
  # exclude nat host b/c we can't log in anyway
  hosts: tag_environment_stage:!tag_function_nat
  sudo: True
  vars:
    secure_dir: ../../../edx-secret/ansible
    local_dir: ../../../edx-secret/ansible/local
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/edxapp.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/stage/users.yml"
  roles:
    - common
    - supervisor

