---
- name: Basic util setup on all hosts
  hosts: ~tag_Name_{{ machine }}_stage
  pre_tasks:
  - fail: msg="This playbook only runnable on 'util' machines"
    when: "'util' not in machine"
  sudo: True
  gather_facts: True
  vars:
    secure_dir: ../../../configuration-secure/ansible
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/common/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/common/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/common/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/common/platform/env.yaml"
    - "{{ secure_dir }}/vars/common/platform/auth.yaml"
    - "{{ secure_dir }}/vars/common/lms/features.yaml"
    - "{{ secure_dir }}/vars/common/lms/microsites.yaml"
    - "{{ secure_dir }}/vars/common/lms/env.yaml"
    - "{{ secure_dir }}/vars/common/lms/auth.yaml"
    - "{{ secure_dir }}/vars/common/cms/env.yaml"
    - "{{ secure_dir }}/vars/common/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/auth.yaml"

    - "{{ secure_dir }}/vars/stage/xqueue.yml"
    - "{{ secure_dir }}/vars/stage/users.yml"
  roles:
    - common
    - supervisor
    - role: user
      tags: users
    - role: edxapp
      celery_worker: True
      devstack: false
    - role: nginx
      nginx_sites:
      - xqueue
      - basic-auth
      tags: 
      - nginx
    - role: xqueue
      xqueue_create_db: "no"
      xqueue_create_users: false
      tags: 
      - xqueue

- name: run the certificate agent on the first util machine only
  hosts: ~tag_Name_util1_stage
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
#    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/certs.yml"
  roles:
    - role: supervisor
      tags: certs
    - role: certs
      tags: certs

- name: run the notifier on the first util machine only
  hosts: ~tag_Name_util1_stage
  sudo: True
  vars:
    secure_dir: "../../../configuration-secure/ansible"
    local_dir: "{{secure_dir}}/local"
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/stage/notifier.yml"
  roles:
    - role: notifier
      tags: notifier
