# run the notifier on the first util machine only
- hosts: ~tag_Name_util10_stage
  sudo: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/notifier.yml"
  roles:
    - supervisor
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier
