- name: Set up staging jumpbox
  hosts: tag_Name_jumpbox_stage
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/users_jumpbox.yml"
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir:  '../../../configuration-secure/ansible/local'
  roles:
    - common
    - supervisor
    - role: user
      user_info:
        - name: jbau
          github: true
          type: admin
        - name: jrbl
          github: true
          type: admin
        - name: caesar2164
          github: true
          type: admin
        - name: dcadams
          github: true
          type: admin
        - name: nparlante
          github: true
        - name: stvstnfrd
          github: true
          type: admin
        - name: jinpa
          github: true
        - name: gbruhns
          github: true
        - name: mondiaz
          github: true
        - name: dylanrhodes
          github: true
        - name: ataki
          github: true
        - name: caijim
          github: true
      tags: users
