---
- hosts: tag_environment_stage:&tag_group_xqueue
  sudo: True
  vars:
    secure_dir: ../../../configuration-secure/ansible
    local_dir: ../../../configuration-secure/ansible/local
  vars_files:
    - "{{ secure_dir }}/vars/stage/xqueue.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/stage/users.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - xqueue
      - basic-auth
    - xqueue
    #- splunkforwarder
