---
- hosts: tag_environment_stage:&tag_group_rabbitmq
  sudo: True
  vars:
    secure_dir: ../../../configuration-secure/ansible
    local_dir: ../../../configuration-secure/ansible/local
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/edxapp.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/stage/users.yml"
  roles:
    - common
    - supervisor
    - rabbitmq
