---
- hosts: tag_Name_forum1_stage
  sudo: yes
  vars:
    secure_dir: ../../../edx-secret/ansible
    local_dir: ../../../edx-secret/ansible/local
  vars_files:
    - "{{secure_dir}}/vars/stage/forum.yml"
  roles:
    - common
    - oraclejdk
    - elasticsearch
    - role: nginx
      nginx_sites:
        - forum
    - forum
