- hosts: localhost
#- hosts: tag_Name_app1_stage
  vars:
    migrate_db: "no"
    not_prod: true
    secure_dir: ../../../edx-secret/ansible
    local_dir: ../../../edx-secret/ansible/local
  vars_files:
    - "{{ secure_dir }}/vars/common/edxapp.yml"
    - "{{ secure_dir }}/vars/stage/edxapp.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/stage/users.yml"
    #- "{{ secure_dir }}/vars/stage/shib.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
      nginx_default_sites:
      - lms
    - edxapp
    - ansible_debug
    #- apache
    #- shibboleth
