---
- name: Basic util setup on all hosts
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  pre_tasks:
  - fail: msg="This playbook only runnable on 'util' machines"
    when: "'util' not in machine"
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir: '../../../configuration-secure/ansible/local'
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/common/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/common/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/common/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/common/platform/env.yaml"
    - "{{ secure_dir }}/vars/common/platform/auth.yaml"
    - "{{ secure_dir }}/vars/common/lms/features.yaml"
    - "{{ secure_dir }}/vars/common/lms/microsites.yaml"
    - "{{ secure_dir }}/vars/common/lms/env.yaml"
    - "{{ secure_dir }}/vars/common/lms/auth.yaml"
    - "{{ secure_dir }}/vars/common/cms/env.yaml"
    - "{{ secure_dir }}/vars/common/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/common/xqueue.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/xqueue.yml"
  roles:
    - role: common
      tags: common
    - role: supervisor
      tags: supervisor
    - role: user
      tags: users
    - role: edxapp
      tags: edxapp
      celery_worker: True
    - role: nginx
      tags: nginx
    - role: xqueue
      tags: xqueue
      xqueue_create_db: "no"
      xqueue_create_users: false

- name: run the certificate agent on the first util machine only
  hosts: ~tag_Name_util1_{{ env }}
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir: '../../../configuration-secure/ansible/local'
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "{{ secure_dir }}/vars/common/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/common/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/common/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/common/platform/env.yaml"
    - "{{ secure_dir }}/vars/common/platform/auth.yaml"
    - "{{ secure_dir }}/vars/common/lms/features.yaml"
    - "{{ secure_dir }}/vars/common/lms/microsites.yaml"
    - "{{ secure_dir }}/vars/common/lms/env.yaml"
    - "{{ secure_dir }}/vars/common/lms/auth.yaml"
    - "{{ secure_dir }}/vars/common/cms/env.yaml"
    - "{{ secure_dir }}/vars/common/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/certs.yml"
  roles:
    - role: supervisor
      tags: certs
      when: env != 'suclass'
    - role: certs
      tags: certs
      when: env != 'suclass'

- name: run the notifier on the second util machine only
  hosts: ~tag_Name_util2_{{ env }}
  sudo: True
  vars:
    secure_dir: "../../../configuration-secure/ansible"
    local_dir: '../../../configuration-secure/ansible/local'
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/{{ env }}/notifier.yml"
  roles:
    - role: notifier
      tags: notifier
      when: env != 'cme' and env != 'stage'

- name: run the notifier on the first util machine only
  hosts: ~tag_Name_util1_{{ env }}
  sudo: True
  vars:
    secure_dir: "../../../configuration-secure/ansible"
    local_dir: '../../../configuration-secure/ansible/local'
    migrate_db: "no"
  vars_files:
    - "roles/common/defaults/main.yml"
    - "roles/supervisor/defaults/main.yml"
    - "{{ secure_dir }}/vars/{{ env }}/notifier.yml"
  roles:
    - role: notifier
      tags: notifier
      when: env == 'stage'
