---
CLUSTER_AMI: 'ami-09d2fb69'
CLUSTER_ELB_HEALTH_CHECK:
  ping_path: '/'
  ping_protocol: http
  ping_port: 80
  response_timeout: 5  # seconds
  interval: 30  # seconds
  unhealthy_threshold: 2  # attempts
  healthy_threshold: 10  # attempts
CLUSTER_ELB_LISTENERS:
  - protocol: http
    load_balancer_port: 80
    instance_port: 80
CLUSTER_ELB_SUBNETS:
  - "{{ CLUSTER_SUBNET_ID }}"
CLUSTER_ELBS:
  - name: "{{ COMMON_DEPLOYMENT }}-elb-{{ CLUSTER_NAME }}"
    subnets: "{{ CLUSTER_ELB_SUBNETS }}"
    listeners: "{{ CLUSTER_ELB_LISTENERS }}"
    health_check: "{{ CLUSTER_ELB_HEALTH_CHECK }}"
    scheme: internal
CLUSTER_INSTANCE_TYPE: t2.micro
CLUSTER_KEY: "{{ COMMON_DEPLOYMENT }}-{{ CLUSTER_NAME }}"
CLUSTER_NAME: 'TODO'
CLUSTER_NUMBER: 1
CLUSTER_REGION: 'us-west-1'
CLUSTER_SECURITY_GROUPS:
  - "{{ COMMON_DEPLOYMENT }}-group-{{ CLUSTER_NAME }}"
  - "{{ COMMON_DEPLOYMENT }}-group-ssh-private"
CLUSTER_SUBNET_ID: subnet-XXXXXX
