---
- name: Deploy elasticsearch
  hosts: tag_role_elasticsearch:&tag_environment_{{ env }}
  sudo: yes
  vars:
    - ELASTICSEARCH_CLUSTERED: true
  roles:
    - common
    - oraclejdk
    - elasticsearch
