---
- name: Set up jumpbox ({{ env }})
  hosts: tag_Name_jumpbox_{{ env }}
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ env }}/jumpbox.yml"
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir:  '../../configuration-secure/ansible/local'
  roles:
    - role: supervisor
      tags: supervisor
