---
- name: run the notifier on the second util machine only (lagunita|suclass)
  hosts: ~tag_Name_util2_{{ env }}
  sudo: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir: '../../configuration-secure/ansible/local'
    migrate_db: 'no'
  vars_files:
    - 'roles/common/defaults/main.yml'
    - 'roles/supervisor/defaults/main.yml'
    - "{{ secure_dir }}/vars/{{ env }}/notifier.yml"
  roles:
    - role: notifier
      tags: notifier
      when: env != 'cme' and env != 'stage'

- name: run the notifier on the first util machine only (stage)
  hosts: ~tag_Name_util1_{{ env }}
  sudo: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir: '../../configuration-secure/ansible/local'
    migrate_db: 'no'
  vars_files:
    - 'roles/common/defaults/main.yml'
    - 'roles/supervisor/defaults/main.yml'
    - "{{ secure_dir }}/vars/{{ env }}/notifier.yml"
  roles:
    - role: notifier
      tags: notifier
      when: env == 'stage'
